Support for masquerade
eduNEXT/seb-openedx pull request #17
Opened 2018-10-25 21:04 UTC by Ivanca

2018-11-01 14:54 UTC, Ivanca commented
@felipemontoya review needed.

2018-11-01 20:07 UTC, felipemontoya requested changes
In terms of the support of masquerade I think we have the right solution. I did however requested many changes in the handling and rendering of responses. Also some refactoring around the permission checks

2018-11-01 20:07 UTC, felipemontoya commented on requirements.txt
> +lxml==3.8.0
this dependency is no longer needed

2018-11-01 20:07 UTC, felipemontoya commented on seb_openedx/middleware.py
>          """ Start point of to d4etermine cms or lms """
```suggestion
        """ Start point of to determine cms or lms """
```

2018-11-01 20:07 UTC, felipemontoya commented on seb_openedx/middleware.py
> +                if masquerade and masquerade.role != 'staff' and permission == AlwaysAllowStaff:
This is strange, we have all the logic to prevent doing things like `permission == AlwaysAllowStaff` and here we are.
I propose the following, lets add an optional kwarg to the `permission().check()` signature, so that we can send the masquerade object. Then we can conduct this logic in the `AlwaysAllowStaff` directly

2018-11-01 20:07 UTC, felipemontoya commented on seb_openedx/middleware.py
> +                    html += masquerade_html
Why are we concatenating here?
Would it be possible to sent the rendering context to the `handle_access_denied` function (or have it in self.context) and only add this `masquerade_html` so that the renderer can put it in the correct place in the html?

2018-11-01 20:07 UTC, felipemontoya commented on seb_openedx/middleware.py
> +        """ if request view support preview_menu or not (not fully accurate) """
I would not say this is "not fully accurate", it is more like: seb-openedx only supports masquerade on this and that views.
```suggestion
        """ Calculates if request view supports the preview_menu or not in this context. Not a perfect match to openedx's internal support"""
```

2018-11-01 20:07 UTC, felipemontoya commented on seb_openedx/middleware.py
> +            js_reposition = render_to_string('seb-reposition-wrapper-preview-menu.html', {})
If we do the `context` change to the renderer, we no longer need this

2018-11-01 20:07 UTC, felipemontoya commented on seb_openedx/middleware.py
> +            masquerade_html = render_to_string('preview_menu.html', context) + js_reposition
Concatenating pieces of HTML is always strange when we have full scale renderers. This won't be necessary

2018-11-01 20:07 UTC, felipemontoya commented on seb_openedx/middleware.py
> +        return force_text(SebCoursewareIndex.as_view()(request, *view_args, **view_kwargs).content)
I believe this wont be necessary after the proposed refactor

2018-11-01 21:18 UTC, Ivanca commented on seb_openedx/middleware.py
> +                    html += masquerade_html
@felipemontoya The renderer at `SebCoursewareIndex.as_view()` is outside our control so there is no clean way to 'put it in the correct place in the html', meaning the JS positioning code is needed.

2018-11-02 20:44 UTC, felipemontoya commented on seb_openedx/middleware.py
> +        if self.get_view_path(request) == 'courseware.masquerade':
Optional: comment

2018-11-02 20:49 UTC, felipemontoya approved these changes
Optional comment inline. Other than that this LGTM :+1:

2018-11-02 21:40 UTC, merged